name: Production Deployment
on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.sha }}

      - name: build
        run: npm install && npm run build

      - name: If deployment fails, delete release & tag
        if: ${{ failure() }}
        run: |
          npm install @octokit/action
          node .github/actions/delete-release.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
