name: Production Deployment
on:
  # workflow_dispatch:
  #   inputs:
  #     sha:
  #       description: "Commit SHA"
  #       required: true
  #     version:
  #       description: "Version"
  #       required: true
  release:
    types:
      - published
      - created

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.event.inputs.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: build
        run: npm install && npm run build

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://test.sekyung.kim

      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.event.inputs.version }}
      #     release_name: ${{ github.event.inputs.version }}
      #     commitish: ${{ github.event.inputs.sha }}
