name: Production Deployment
on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/sekyungk/deploy-poc/releases/latest
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data.id }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: build
        run: npm install && npm run build

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://test.sekyung.kim
