name: Production Deployment
on:
  workflow_dispatch:
    inputs:
      sha:
        description: "Commit SHA"
        required: true
      version:
        description: "Version"
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.sha }}

      - name: build
        run: npm install && npm run buil

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          commitish: ${{ github.event.inputs.sha }}
