name: Staging Deployment

on:
  push:
    branches:
      - master
      - staging-**

jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: npm install && npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Check Main Staging
        if: ${{ github.ref == 'refs/heads/master'}}
        run: aws s3 sync ./build s3://staging.sekyung.kim

      - name: Check Main Staging
        if: contains(github.ref, 'staging-')
        run: aws s3 sync ./build s3://${GITHUB_REF#refs/heads/}.sekyung.kim

      - name: Update Deployment Reference
        run: node .github/actions/update-ref.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          deployment: staging
          sha: ${{ github.event.inputs.sha }}
