name: Staging Deployment

on:
  push:
    branches:
      - master
      - staging-**

jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: npm install && npm run build

      - name: Check Main Staging
        if: ${{ github.ref == 'refs/heads/master'}}
        run: echo "Deploying to production server on branch $GITHUB_REF"

      - name: Check Main Staging
        if: ${{ github.ref == 'refs/heads/staging-**' }}
        run: echo "Deploying to production server on branch $GITHUB_REF"
