name: Staging Deployment

on:
  push:
    branches:
      - master

jobs:
  d:
    name: Deploy Staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: npm install && npm run build

      - name: TEST
        run: echo ${{ github.event.deployment.id }}
