name: Staging Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: "a"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: npm install && npm run build

      - name: Update Deployment Reference
        run: node .github/actions/update-ref.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          deployment: staging
          sha: ${{ github.sha }}
